### ISSUE TITLE
PLEASE FIX

### ISSUE THREAD

**Issue by RickOttolino** [LinkedInLearning/learning-linux-command-line-3005201#2] opened 2022-09-14 21:23 UTC
VBoxGuestAdditions does not work and ZIP file with Exercises are unavailable

## Issue Overview
VBoxGuestAdditions does not work and ZIP file with Exercises are unavailable

## Describe your environment
 Running Ubuntu as a VM on a WIN10 Machine

## Steps to Reproduce

1.
2.
3.
4.

**Comment by hiteshujani2002** [comment] 2022-09-28 02:56
I am also facing the same issue...

**Comment by scottsimpson** [comment] 2022-10-17 18:38
Closing as duplicate of #1.

**Closed by scottsimpson** 2022-10-17 18:38 UTC
